version: v1.0.0

dataset:
  type: custom

  image_reader:
    type: opencv
    kwargs:
      image_dir: ./data/MVTec_ad/mvtec_anomaly_detection
      color_mode: RGB

  train:
    meta_file: ./data/MVTec_ad/train.json
    rebalance: False
    hflip: False
    vflip: False
    rotate: False

  test:
    meta_file: ./data/MVTec_ad/test.json

  input_size: [336, 336] # [h, w]
  crop_size: [336, 336]
  pixel_mean: [0.485, 0.456, 0.406]
  pixel_std: [0.229, 0.224, 0.225]
  batch_size: 16
  workers: 4 # number of workers of dataloader for each process
